---
- name: Install nginx
  apt:
    name: nginx

- name: Change config
  template:
    src: "{{ role_path }}/templates/nginx.conf.j2"
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: 'restart nginx'